### ISSUE TITLE
Pretrained models

### ISSUE THREAD

**Issue by lhr18716032695** [MathiasGruber/PConv-Keras#11]
thanks a lot for sharing yr code.I spent many time to use my device to train.Can you publish your pretrained models.

**Comment by ZDD2009** [comment]
@lhr18716032695 do you have the pretrained models?thank you very much!

**Comment by ZDD2009** [comment]
@MathiasGruber where can i download the pretrained models? i need your help,thank you !

**Comment by MathiasGruber** [comment]
I've updated the readme with links to pretrained networks. I've not gotten them to completely converge though, as I'm also somewhat limited on computational resources.
