### ISSUE TITLE
how did you found out what U-net to use?

### ISSUE THREAD

**Issue by cuevas1208** [MathiasGruber/PConv-Keras#18]
![image](https://user-images.githubusercontent.com/13240742/54218968-c95e2f00-44ab-11e9-9cc9-212d048862e7.png)

When I was reading the paper reference 11 is Isola, P., Zhu, J.Y., Zhou, T., Efros, A.A.: Image-to-image translation with conditional adversarial networks. arXiv preprint (2017).

Are you using a conditional adversarial network?

**Comment by MathiasGruber** [comment]
In version 1 on arxiv the section goes like this:

![image](https://user-images.githubusercontent.com/7893509/54253779-15af7a80-4551-11e9-8ee7-47b73f243c83.png)

**Comment by cuevas1208** [comment]
Thank you for that
