### ISSUE TITLE
ValueError: invalid literal for int() with base 10: 'h5'

### ISSUE THREAD

**Issue by anonym24** [MathiasGruber/PConv-Keras#25]
I'm trying to run (from step 5 ipynb):

```
from libs.pconv_model import PConvUnet
model = PConvUnet(vgg_weights=None, inference_only=True)
model.load(r"/media/user/PConv-Keras/pconv_imagenet.h5", train_bn=False)
```

But it fails with `ValueError: invalid literal for int() with base 10: 'h5'` error:

```
ValueError                                Traceback (most recent call last)
<ipython-input-11-adc04f0f404a> in <module>
      1 from libs.pconv_model import PConvUnet
      2 model = PConvUnet(vgg_weights=None, inference_only=True)
----> 3 model.load(r"/media/user/PConv-Keras//pconv_imagenet.h5", train_bn=False)

/media/user/PConv-Keras/libs/pconv_model.py in load(self, filepath, train_bn, lr)
    266 
    267         # Load weights into model
--> 268         epoch = int(os.path.basename(filepath).split('.')[1].split('-')[0])
    269         assert epoch > 0, "Could not parse weight file. Should include the epoch"
    270         self.current_epoch = epoch

ValueError: invalid literal for int() with base 10: 'h5'
```

**Comment by anonym24** [comment]
p.s. I'm trying this pretrained weight https://drive.google.com/file/d/1OdbuNJj4gV9KUoknQG063jJrJ1srhBvU/view

**Comment by deepankarc** [comment]
The name convention of the model weights file has the date and epoch. For simplicity just change the name from `pconv_imagenet.h5` to `pconv_imagenet.26-1.07.h5`

**Comment by anonym24** [comment]
@deepankarc yes, I've already tried it.

It almost worked but it just stays at [*] and nothing happens at all, this step never finishes

**Comment by anonym24** [comment]
finally it worked, though I tried on Windows this time

**Comment by zhaoxin111** [comment]
> finally it worked, though I tried on Windows this time

Hi, I also encountered this problem, how do you solve it?

**Comment by Harisahmad1881** [comment]
facing same issue. but when changed the name to `pconv_imagenet.26-1.01.h5` 
it fails with 
![s](https://user-images.githubusercontent.com/63928427/86494991-d4b82680-bd90-11ea-8eed-6b0bdbe48691.png)
`ValueError: Layer #0 (named "p_conv2d_513" in the current model) was found to correspond to layer p_conv2d_49 in the save file. However the new layer p_conv2d_513 expects 3 weights, but the saved weights have 2 elements.`
@anonym24  @deepankarc

**Comment by Kirstihly** [comment]
> facing same issue. but when changed the name to `pconv_imagenet.26-1.01.h5`
> it fails with
> ![s](https://user-images.githubusercontent.com/63928427/86494991-d4b82680-bd90-11ea-8eed-6b0bdbe48691.png)
> `ValueError: Layer #0 (named "p_conv2d_513" in the current model) was found to correspond to layer p_conv2d_49 in the save file. However the new layer p_conv2d_513 expects 3 weights, but the saved weights have 2 elements.`
> @anonym24 @deepankarc

@Harisahmad1881 This is because of the TF version. Please try pip install -r requirements.txt with all versions specified by the author.
