### ISSUE TITLE
question about the partial convolutional layer

### ISSUE THREAD

**Issue by yuzehui1996** [MathiasGruber/PConv-Keras#7]
hey, thanks for your codes.
Do you know about the partial convolutional layer in the paper? I have seen your architecture image showed in Readme, but I can't explain that  an image which size is 512*512*3, and is input into a partial layer ,and the output's size is 256*256*64.The kernel is 7*7,and the strides is 2.I don't get why 512*512 comes to 256*256? Do you have any idea? Thanks!

**Comment by TrinhQuocNguyen** [comment]
Hi yuzehui1996,
512x 512 -> 256x256 with stride=2 because the code uses padding= 'same'

**Comment by NerminSalem** [comment]
@TrinhQuocNguyen how did u run the code? thanks alot

**Comment by TrinhQuocNguyen** [comment]
@NerminSalem
You have to modify the directory paths to your own folders.
