### ISSUE TITLE
The predicted image is in almost null (all pixels are the same in grey)

### ISSUE THREAD

**Issue by bytemani** [MathiasGruber/PConv-Keras#72]
Hi, everyone. I am tring to train the model on my own datasets and wanna know if everything is going well. 
So, after few steps, I use the model like this:
"model = PConvUnet(vgg_weights=None, inference_only=True)
model.load(r"D:\projects_test\PConv-Keras-master\data\logs\myDataset_phase1\weights.01-7.00.h5", train_bn=False)"
and weights.01-7.00.h5 the midresult of the training.
However, it seems the prediction does not work well as the title depicted. Does anyone know what is going wrong or not? Thank you.

**Comment by bytemani** [comment]
solved.

**Comment by patodichayan** [comment]
@bytemani how did you solve it ?!
