### ISSUE TITLE
why do the generated mask are different from the original paper?

### ISSUE THREAD

**Issue by micklexqg** [MathiasGruber/PConv-Keras#8]
hi, thanks for your work. i note that the code generates a random irregular mask with lines, circles and elipses. I wonder do you follow the method of generating masks in the original paper?

**Comment by MathiasGruber** [comment]
Nope, not at the moment, I took a short-cut on that one for now, although I think following the original paper would be a good idea. Feel free to create a pull-request for that, I'm not sure I'll have time to attempt an implementation.
